// Generated by CoffeeScript 1.8.0
(function() {
  var handleCacheEventUpdateReady;

  handleCacheEventUpdateReady = function(e) {
    if (window.applicationCache.status === window.applicationCache.UPDATEREADY) {
      window.applicationCache.swapCache();
      if (confirm('A new version of this application is available. Load it?')) {
        return window.location.reload();
      }
    }
  };

  window.addEventListener('load', function(e) {
    return window.applicationCache.addEventListener('updateready', handleCacheEventUpdateReady, false);
  });

}).call(this);

//# sourceMappingURL=bp-cache.js.map
