// Generated by CoffeeScript 1.8.0
(function() {
  window.Log = {
    DEBUG: {
      id: "DEBUG",
      prio: 0
    },
    INFO: {
      id: "INFO",
      prio: 1
    },
    WARN: {
      id: "WARN",
      prio: 2
    },
    ERROR: {
      id: "ERROR",
      prio: 3
    },
    FATAL: {
      id: "FATAL",
      prio: 4
    },
    enter: function(name) {
      return this.info("" + name + "() enter");
    },
    exit: function(name) {
      return this.info("" + name + "() exit");
    },
    debug: function(text) {
      return this.log(Log.DEBUG, text);
    },
    info: function(text) {
      return this.log(Log.INFO, text);
    },
    warn: function(text) {
      return this.log(Log.WARN, text);
    },
    error: function(text) {
      return this.log(Log.ERROR, text);
    },
    fatal: function(text) {
      return this.log(Log.FATAL, text);
    },
    log: function(level, text) {
      if (level.prio >= this.level.prio) {
        return console.log("[" + level.id + "]: " + text);
      }
    }
  };

  Log.level = Log.WARN;

  Log.info("Logging initialized.");

}).call(this);

//# sourceMappingURL=bp-logging.js.map
